# Generated by Django 3.2.4 on 2022-04-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_alter_expense_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.AddField(
            model_name='expense',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
