# Generated by Django 3.2.4 on 2022-04-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0005_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='user',
            new_name='owner',
        ),
    ]
