# Generated by Django 4.0.3 on 2022-04-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0002_alter_expense_user_alter_income_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='myuser',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='user',
            new_name='myuser',
        ),
    ]
