# Generated by Django 4.0.3 on 2022-04-04 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Expense', '0003_rename_user_expense_myuser_rename_user_income_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='myuser',
        ),
        migrations.RemoveField(
            model_name='income',
            name='myuser',
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
