# Generated by Django 4.0.3 on 2022-04-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
