# Generated by Django 4.0.3 on 2022-04-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_rename_is_staff_myuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
